import Document, { Html, Head, Main, NextScript } from 'next/document'

export default class CustomDocument extends Document {
    render() {
        return (
            <Html>
                <Head>
                    <title>MovieFLIX</title>
                    <meta name="description" content="Generated by create next app" />
                    <link className="object-contain" rel="icon" href="/movie_logo.webp" />
                </Head>
                <body>
                    <Main />
                </body>
                <NextScript />
            </Html>
        )
    }
}